### ISSUE TITLE
Flare errors

### ISSUE THREAD

**Issue by Dannylowney** [Supmenow/sup-issues#45] opened 2016-05-16 14:11 UTC
When I get an error on sending a flare (didn't choose activity/location/neither) and then return to create a flare screen, the launch button disappears in to a loading circle

**Comment by alexsup** [comment] 2016-05-16 14:15
Thanks @Dannylowney.

@jcampbell05 Closing as duplicate of #44

**Closed by alexsup** 2016-05-16 14:15 UTC
