### ISSUE TITLE
My friends disappear when I hide

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#27] opened 2016-05-12 16:00 UTC
When I click show it takes time for them to come back.

Friends are not in sync with the hide button. I can sometimes see friends in dark mode and not in friends mode.

**Comment by jcampbell05** [comment] 2016-05-12 16:04
Duplicate of https://github.com/Supmenow/sup-issues/issues/7

**Closed by jcampbell05** 2016-05-12 16:04 UTC
Labels: defect
